// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfzzjnpkqbljhfdbbrqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmenpqbnBrcWJsamhmZGJicnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODk0NjksImV4cCI6MjA1OTE2NTQ2OX0.mgQoskAa0iy8t-lijNPqpUGlpm6Dc6WN0l7TM0qNeQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);