
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://vfzzjnpkqbljhfdbbrqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmenpqbnBrcWJsamhmZGJicnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODk0NjksImV4cCI6MjA1OTE2NTQ2OX0.mgQoskAa0iy8t-lijNPqpUGlpm6Dc6WN0l7TM0qNeQk";

// Create a custom type that augments the generated types to include our new tables
export type CustomDatabase = Database & {
  public: {
    Tables: {
      business_insights: {
        Row: {
          id: string;
          user_id: string;
          industry: string | null;
          business_model: string | null;
          description: string | null;
          ai_summary: string | null;
          ai_processing_status: string;
          version: number;
          previous_versions: any | null;
          error_log: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          industry?: string | null;
          business_model?: string | null;
          description?: string | null;
          ai_summary?: string | null;
          ai_processing_status?: string;
          version?: number;
          previous_versions?: any | null;
          error_log?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          industry?: string | null;
          business_model?: string | null;
          description?: string | null;
          ai_summary?: string | null;
          ai_processing_status?: string;
          version?: number;
          previous_versions?: any | null;
          error_log?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "business_insights_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ]
      };
      ai_usage_stats: {
        Row: {
          id: string;
          user_id: string | null;
          function_name: string;
          request_type: string | null;
          model: string | null;
          status: string | null;
          tokens_used: number | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          function_name: string;
          request_type?: string | null;
          model?: string | null;
          status?: string | null;
          tokens_used?: number | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          function_name?: string;
          request_type?: string | null;
          model?: string | null;
          status?: string | null;
          tokens_used?: number | null;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ai_usage_stats_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ]
      };
    } & Database['public']['Tables'];
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
